[pytest]
testpaths = tests
addopts = 
    -v
    --strict-markers
    --tb=short
    --alluredir=allure-results
    --clean-alluredir
markers =
    smoke: smoke tests
    regression: regression tests
    calculator: calculator tests
    saucedemo: saucedemo tests
